FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run dev

#stage 2 final build
FROM nginx:alpine
COPY --from=build /app/build/ /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/dafault.conf.template
COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx","-g","daemon off"]